server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/students/**
        - id: school-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
